// ⚠️ CONVENTION FOR ADDING BOOKS (agents: follow this exactly):
//  • ADD NEW BOOKS AT THE TOP of this array (index 0), so they appear first.
//  • Use ONLY the SHORT title the user gives — never the full subtitle.
//  • Keep the same { id, title, author, notes } shape as every other entry so
//    the card title renders in the same gray as the rest (no special styling).
//  • The cover lives at assets/books/<id>.jpg.
const BOOKS = [
  { id: '2081', title: '2081', author: "Gerard K. O'Neill", notes: '' },
  { id: 'the-high-frontier', title: 'The High Frontier', author: "Gerard K. O'Neill", notes: '' },
  { id: 'trillion-dollar-coach', title: 'Trillion Dollar Coach', author: 'Eric Schmidt', notes: '' },
  { id: 'what-we-owe-the-future', title: 'What We Owe the Future', author: 'William MacAskill', notes: '' },
  { id: 'the-optimist', title: 'Sam Altman', author: 'Keach Hagey', notes: '' },
  { id: 'our-oriental-heritage', title: 'The Story of Civilization Our Oriental Heritage', author: 'Will Durant', notes: '' },
  { id: 'the-case-for-space', title: 'The case for space', author: 'Robert Zubrin', notes: '' },
  { id: 'spacefarers', title: 'Spacefarers', author: 'Christopher Wanjek', notes: '' },
  { id: 'superintelligence', title: 'Superintelligence', author: 'Nick Bostrom', notes: '' },
  { id: 'the-three-body-problem', title: 'The Three-Body Problem', author: 'Cixin Liu', notes: '' },
  { id: 'the-space-barons', title: 'The Space Barons', author: 'Christian Davenport', notes: '' },
  { id: 'skunk-works', title: 'Skunk Works', author: 'Ben R. Rich', notes: '' },
  { id: 'how-to-build-your-own-space-ship', title: 'How to Build Your Own Space Ship', author: 'Piers Bizony', notes: '' },
  { id: 'the-aesthetic-brain', title: 'The Aesthetic Brain', author: 'Anjan Chatterjee', notes: '' },
  { id: 'breakneck', title: 'Breakneck', author: 'Dan Wang', notes: '' },
  { id: 'the-goal', title: 'The goal', author: 'Eliyahu Goldratt', notes: '' },
  { id: 'the-book-of-elon', title: 'The Book of Elon', author: 'Eric Jorgenson', notes: '' },
  { id: 'the-algorithm', title: 'The Algorithm', author: 'Jon McNeill', notes: '' },
  { id: 'decline-and-fall-roman-empire', title: 'The Decline and Fall of The Roman Empire', author: 'Moses Hadas', notes: '' },
  { id: 'ignition', title: 'Ignition!', author: 'John Drury Clark', notes: '' },
  { id: 'start-with-why', title: 'Start with Why', author: 'Simon Sinek', notes: '' },
  { id: 'explore-create', title: 'Explore/Create', author: 'Richard Garriott', notes: '' },
  { id: 'skin-in-the-game', title: 'Skin in the Game', author: 'Nassim Nicholas Taleb', notes: '' },
  { id: 'liftoff', title: 'Liftoff', author: 'Eric Berger', notes: '' },
  { id: 'the-machine-that-changed-the-world', title: 'The Machine That Changed the World', author: 'James P. Womack', notes: '' },
  { id: 'the-biggest-ideas-in-the-universe', title: 'The Biggest Ideas in the Universe', author: 'Sean M. Carroll', notes: '' },
  { id: 'from-poverty-to-power', title: 'From Poverty To Power', author: 'James Allen', notes: '' },
  { id: 'the-wealth-of-nations', title: 'The Wealth of Nations Ⅰ', author: 'Adam Smith', notes: '' },
  { id: 'structures', title: "Structures: Or Why Things Don't Fall Down", author: 'J.E. Gordon', notes: '' },
  { id: 'the-art-of-the-deal', title: 'The Art Of The Deal', author: 'Donald J Trump', notes: '' },
  { id: 'the-ride-of-a-lifetime', title: 'The Ride of A Lifetime', author: 'Robert Iger', notes: '' },
  { id: 'waiting-for-godot', title: 'Waiting for Godot', author: 'Samuel Beckett', notes: '' },
  { id: 'the-machine-stops', title: 'The Machine Stops', author: 'E. M. Forster', notes: '' },
  { id: 'how-to-be-a-genius', title: 'How to be a Genius or the Science of Being Great', author: 'Wallace D. Wattles', notes: '' },
  { id: 'how-to-get-what-you-want', title: 'How To Get What You Want', author: 'Wallace D. Wattles', notes: '' },
  { id: 'einsteins-relativity', title: "Einstein's Relativity and the Quantum Revolution", author: 'Richard Wolfson', notes: '' },
  { id: 'hannibal', title: 'Hannibal', author: 'Philip Freeman', notes: '' },
  { id: 'the-art-of-war', title: 'The Art of War', author: 'Sun Tzu', notes: '' },
  { id: 'blitzscaling', title: 'Blitzscaling', author: 'Chris Yeh and Reid Hoffman', notes: '' },
  { id: 'screw-it-lets-do-it', title: "Screw It, Let's Do It!", author: 'Sir Richard Branson', notes: '' },
  { id: 'lying', title: 'Lying', author: 'Sam Harris', notes: '' },
  { id: 'the-almanack-of-naval-ravikant', title: 'The Almanack of Naval Ravikant', author: 'Eric Jorgenson', notes: '' },
  { id: 'foundation', title: 'Foundation', author: 'Isaac Asimov', notes: '' },
  { id: 'i-robot', title: 'I, Robot', author: 'Isaac Asimov', notes: '' },
  { id: 'rocket-propulsion-elements', title: 'Rocket Propulsion Elements', author: 'George P. Sutton', notes: '' },
  { id: 'becoming', title: 'Becoming', author: 'Michelle Obama', notes: '' },
  { id: 'something-deeply-hidden', title: 'Something Deeply Hidden', author: 'Sean Caroll', notes: '' },
  { id: 'water', title: 'Water', author: 'Giulio Boccaletti', notes: '' },
  { id: 'house-of-huawei', title: 'House of Huawei', author: 'Eva Dou', notes: '' },
  { id: 'project-hail-mary', title: 'Project Hail Mary', author: 'Andy Weir', notes: '' },
  { id: 'the-nvidia-way', title: 'The Nvidia Way', author: 'Tae Kim', notes: '' },
  { id: 'excellent-advice-for-living', title: 'Excellent Advice for living', author: 'Kevin Kelly', notes: '' },
  { id: 'titan', title: 'Titan The Life of John D. Rockefeller', author: 'Ron Chernow', notes: '' },
  { id: 'the-meaning-of-it-all', title: 'The Meaning of it All', author: 'Richard P. Feynman', notes: '' },
  { id: 'make-something-wonderful', title: 'Make Something Wonderful', author: 'Steve Jobs', notes: '' },
  { id: 'poor-charlies-almanack', title: "Poor Charlie's Almanack", author: 'Charles T. Munger', notes: '' },
  { id: 'wizard', title: 'Wizard The Life and Time of Nikola Tesla', author: 'Marc J. Seifer', notes: '' },
  { id: 'build', title: 'Build', author: 'Tony Fadell', notes: '' },
  { id: 'super-founders', title: 'Super Founders', author: 'Ali Tamaseb', notes: '' },
  { id: 'a-promised-land', title: 'A Promised Land', author: 'Barack Obama', notes: '' },
  { id: 'hitler', title: 'Hitler', author: 'Ian Kershaw', notes: '' },
  { id: 'my-life-and-work', title: 'My Life and Work', author: 'Henry Ford', notes: '' },
  { id: 'the-autobiography-of-benjamin-franklin', title: 'The Autobiography of Benjamin Franklin', author: 'Benjamin Franklin', notes: '' },
  { id: 'rework', title: 'Rework', author: 'Jason Fried', notes: '' },
  { id: 'how-to-succeed-mr-beast', title: 'How to succeed in Mr Beast production', author: 'James Stephen Donaldson', notes: '' },
  { id: 'blockchain-basics', title: 'Blockchain Basics', author: 'Daniel Drescher', notes: '' },
  { id: 'einstein', title: 'Einstein', author: 'Walter Isaacson', notes: '' },
  { id: 'steve-jobs', title: 'Steve Jobs', author: 'Walter Isaacson', notes: '' },
  { id: 'elon-musk', title: 'Elon Musk', author: 'Walter Isaacson', notes: '' },
  { id: 'the-innovators', title: 'The Innovators', author: 'Walter Isaacson', notes: '' },
  { id: 'the-code-breaker', title: 'The Code Breaker', author: 'Walter Isaacson', notes: '' },
  { id: 'leonardo-da-vinci', title: 'Leonardo da Vinci', author: 'Walter Isaacson', notes: '' },
  { id: 'that-will-never-work', title: 'That will never work', author: 'Marc Randolph', notes: '' },
  { id: 'atomic-habits', title: 'Atomic Habits', author: 'James Clear', notes: '' },
  { id: 'the-inevitable', title: 'The Inevitable', author: 'Kevin Kelly', notes: '' },
  { id: 'the-innovators-dilemma', title: "The Innovator's Dilemma", author: 'Clayton M. Christensen', notes: '' },
  { id: 'the-inner-game-of-tennis', title: 'The Inner Game of Tennis', author: 'Timothy Gallwey', notes: '' },
  { id: 'the-22-immutable-laws-of-marketing', title: 'The 22 Immutable Laws Of Marketing', author: 'Al Ries', notes: '' },
  { id: 'how-to-tell-a-story', title: 'How to Tell a Story', author: 'Meg Bowles', notes: '' },
  { id: 'think-and-grow-rich', title: 'Think and Grow rich', author: 'Napoleon Hill', notes: '' },
  { id: 'the-diary-of-a-ceo', title: 'The Diary Of A CEO', author: 'Steven Bartlett', notes: '' },
  { id: '100-million-dollar-leads', title: '100 Million Dollar Leads', author: 'Alex Hormozi', notes: '' },
  { id: '100-million-dollar-offers', title: '100 Million Dollar Offers', author: 'Alex Hormozi', notes: '' },
  { id: 'zero-to-one', title: 'Zero to One', author: 'Peter Thiel', notes: '' },
  { id: 'blue-ocean-strategy', title: 'Blue Ocean Strategy', author: 'W. Chan Kim', notes: '' },
  { id: 'how-to-win-friends', title: 'How to win friends and influence people', author: 'Dale Carnegie', notes: '' },
  { id: 'the-5-levels-of-leadership', title: 'The 5 Levels of Leadership', author: 'John C. Maxwell', notes: '' },
  { id: 'managing-oneself', title: 'Managing Oneself', author: 'Peter Drucker', notes: '' },
  { id: 'evolution-series', title: 'Evolution Series', author: 'Thomas Thiemeyer', notes: '' },
  { id: 'mostly-harmless', title: 'Mostly Harmless', author: 'Douglas Adams', notes: '' },
  { id: 'so-long-and-thanks-for-all-the-fish', title: 'So Long and Thanks For All the Fish', author: 'Douglas Adams', notes: '' },
  { id: 'life-the-universe-and-everything', title: 'Life the Universe and Everything', author: 'Douglas Adams', notes: '' },
  { id: 'the-restaurant-at-the-end-of-the-universe', title: 'The Restaurant at the End of the Universe', author: 'Douglas Adams', notes: '' },
  { id: 'the-hitchhikers-guide-to-the-galaxy', title: "The Hitchhiker's guide to the galaxy", author: 'Douglas Adams', notes: '' },
  { id: 'ijon-tichy-raumpilot', title: 'Ijon Tichy Raumpilot', author: 'Stanisław Lem', notes: '' },
];

if (typeof window !== 'undefined') {
  window.BOOKS = BOOKS;
}

if (typeof module !== 'undefined') {
  module.exports = { BOOKS };
}
